### ISSUE TITLE
`UtilityAIArea3DVisibilitySensor` never finds unoccluded areas

### ISSUE THREAD

**Issue by citizenken** [JarkkoPar/Utility_AI#8]
This might be my misunderstanding, but based on the documentation, if `do_occlusion_test == true` and the `collision_mask` is set to something that could be blocking a line of sight to an area (ex. setting it to 1 for scenery), then I should see unoccluded results in `unoccluded_areas`.

In my scene, I have these settings set as defined above, and have an area that is being correctly detected as overlapping a couple of meters away from the origin point and not being blocked by anything. When `num_entities_found` is checked, no entities are found. I don't know CPP or how Godot-CPP is supposed to work, but [this if statement](https://github.com/JarkkoPar/Utility_AI/blob/main/src/agent_behaviours/sensors/area3d_visibility.cpp#L251-L264) seems potentially wrong? Based on my understanding, I would expect this:
```
Dictionary results = dss->intersect_ray( params );
if( !results.is_empty() ) { <-- this currently is checking if results _is_ empty
    _unoccluded_areas.push_back(area);
    _squared_distances_to_unoccluded_areas.push_back(distance_squared);
    if( _closest_unoccluded_area_index == -1 ) {
        _closest_unoccluded_area_index = found_unoccluded_areas;
        closest_unoccluded_area_distance = distance_squared;
    } else if( closest_unoccluded_area_distance > distance_squared ) {
        _closest_unoccluded_area_index = found_unoccluded_areas;
        closest_unoccluded_area_distance = distance_squared;
    }
    ++found_unoccluded_areas;
    ++_num_entities_found;
}
```
since the body of the statement adds the area to the unoccluded areas and increments them. I saw the same logic in the 2D visibility sensor as well.

**Comment by citizenken** [comment]
Looking at it more closely, I was wrong about the `!results.is_empty()` call, because the occluding collision mask is what is being tested with the raycast. Since that is the case, we actually do want if the results are empty.

**Comment by JarkkoPar** [comment]
Hi, thanks for creating an issue about this question and commenting your conclusion, as it may help others in a similar situation. Good luck with your project!
